screen  = "screen"
command = """
	gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "[{'Gdk/WindowScalingFactor', <$scale}>}]"
	gsettings set org.gnome.desktop.interface scaling-factor $scale
	killall -SIGQUIT gnome-shell
"""
events = ["RRScreenChangeNotify"]

[[scale]]
width = 1080
scale = 1

[[scale]]
height = 2160
scale  = 2
